//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVenta.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBSistemVentaEntities : DbContext
    {
        public DBSistemVentaEntities()
            : base("name=DBSistemVentaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<Purchase> Purchase { get; set; }
        public virtual DbSet<Purchase_Detail> Purchase_Detail { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
        public virtual DbSet<Sale_Detail> Sale_Detail { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        public virtual ObjectResult<sp_ListUsers_Result> sp_ListUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListUsers_Result>("sp_ListUsers");
        }
    }
}
