//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVenta.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissions
    {
        public int PermissionId { get; set; }
        public Nullable<int> RolId { get; set; }
        public string NameMenu { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual ROL ROL { get; set; }
    }
}
