//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVenta.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.Purchase_Detail = new HashSet<Purchase_Detail>();
        }
    
        public int PurchaseId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public string TypeDocument { get; set; }
        public string NumberDocument { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual Provider Provider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Detail> Purchase_Detail { get; set; }
        public virtual Users Users { get; set; }
    }
}
