//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVenta.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.Sale_Detail = new HashSet<Sale_Detail>();
        }
    
        public int SaleId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string TypeDocument { get; set; }
        public string NumberDocument { get; set; }
        public string DocumentClient { get; set; }
        public string NameClient { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<decimal> Turned { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale_Detail> Sale_Detail { get; set; }
        public virtual Users Users { get; set; }
    }
}
