//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVenta.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_Detail
    {
        public int SaleDetailId { get; set; }
        public Nullable<int> SaleId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
